version: "3"
services:
  # app
  app:
    container_name: appjava21
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: 21
        USERNAME: aoba
        USER_UID: 1000
        USER_GID: 1000
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
