version: "3"
services:
  # mysql
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    build:
      context: ./mysql/
    env_file:
      - ./mysql/db.env
    ports:
      - "${DB_PORT-3306}:3306"
    volumes:
      - mysql-local:/var/lib/mysql # 実データの永続化（名前付きボリュームを指定）
  # java
  java:
    container_name: ${COMPOSE_PROJECT_NAME}-java
    build:
      context: ./java/
      args:
        JAVA_VERSION: ${JAVA_VERSION}
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    env_file:
      - ./mysql/db.env
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    depends_on:
      - mysql # mysql の後で起動

# 名前付きボリューム
volumes:
  mysql-local:
