version: "3"
services:
  # app
  app:
    container_name: javaapp
    build:
      context: ./java/
      args:
        JAVA_VERSION: ${JAVA_VERSION}
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
